#!/usr/bin/env bash
PFX="$(mktemp -p $HOME tmp.mail.$(date --iso=seconds).XXXXXX)" || exit 1
BIN="$(dirname "$(realpath "$0")")" || exit 1

[ -r wallet.json ] || python3 "$BIN"/make_keys wallet.json || exit 1

GW=https://aoweave.tech

cat > "$PFX".eml

MIME=text/plain # more useful for quick viewing
MIME2=message/rfc822

# Script fails if the data item cannot be uploaded.

python3 "$BIN"/ditem_load.py wallet.json "$PFX".eml --tags Content-Type=$MIME Content-Type=$MIME2 > "$PFX".json || { rm "$PFX".eml; exit 1; }

# The receipt and actual SMTP are then done in the background for responsivity,
# so an interface may report success with the actual mail not sent atm.

{
	RCPT=$(python3 "$BIN"/ditem_load.py wallet.json "$PFX".json --tags Content-Type=application/json | jq -r .id)
	ID=$(jq -r .id < "$PFX".json)
	NOW=$(jq -r .start_block < "$PFX".json)
	BY=$(jq -r .deadlineHeight < "$PFX".json)

	cat >> "$PFX".eml <<EOF &&

$GW/$ID#$NOW#$BY
$GW/$RCPT
I am not affiliated with $GW .
EOF
	while ! msmtp --read-envelope-from --read-recipients -t < "$PFX".eml
	do
		sleep 1
	done
	#RC=$?
	rm -f "$PFX".eml
	#exit $RC # exit status presently discarded

} </dev/null >$PFX.log 2>&1 &

disown -r
