# generated by chatgpt free plan 4o 2025-04-30
{
  description = "PyArweave Python package";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };

        python = pkgs.python3;
        pythonPackages = python.pkgs;

        erlang_py = pythonPackages.buildPythonPackage {
          pname = "erlang-py";
          version = "2.0.7";
          src = pkgs.fetchFromGitHub {
            owner = "okeuday";
            repo = "erlang_py";
            rev = "v2.0.7";
            hash = "sha256-f0DDbzw+qvvk8xOg5YcdW2DMKCrOT60OKy+9rF5PKu4=";
          };
        };

        pyArweave = pythonPackages.buildPythonPackage {
          pname = "PyArweave";
          version = "0.6.1";

          src = ./.;

          format = "setuptools";

          propagatedBuildInputs = with pythonPackages; [
            arrow
            python-jose
            pycryptodome
            requests
            erlang_py
          ];

          doCheck = false;
        };
      in {
        packages.default = pyArweave;
        devShells.default = pkgs.mkShell {
          buildInputs = [ pyArweave ];
        };
      });
}
